### ISSUE TITLE
tab bar doesnt change color

### ISSUE THREAD

**Issue by korbosoft** [catppuccin/wezterm#12]
![image](https://user-images.githubusercontent.com/47117026/224770280-b6403d09-33b5-4972-bf0a-42a0d7654f0a.png)
if you need more details, feel free to ask

**Comment by nekowinston** [comment]
Please use
```lua
return {
  use_fancy_tab_bar = false,
}
```
if you expect to see a styled tab bar appearance. See the [docs](https://wezfurlong.org/wezterm/config/lua/config/use_fancy_tab_bar.html#use_fancy_tab_bar--true).

The "fancy tab bar" has less options available: https://wezfurlong.org/wezterm/config/appearance.html#native-fancy-tab-bar-appearance

If you want to style your retro tab bar, feel free to have a look [at my dotfiles](https://github.com/nekowinston/dotfiles/blob/main/home/apps/wezterm/bar.lua):
<img width="755" alt="image" src="https://user-images.githubusercontent.com/79978224/224771749-3ba6e5db-47d5-453f-8de4-38ff75d1aa38.png">

**Comment by korbosoft** [comment]
Thanks!

**Comment by nonetrix** [comment]
> Please use
> 
> ```lua
> return {
>   use_fancy_tab_bar = false,
> }
> ```
> 
> if you expect to see a styled tab bar appearance. See the [docs](https://wezfurlong.org/wezterm/config/lua/config/use_fancy_tab_bar.html#use_fancy_tab_bar--true).
> 
> The "fancy tab bar" has less options available: https://wezfurlong.org/wezterm/config/appearance.html#native-fancy-tab-bar-appearance
> 
> If you want to style your retro tab bar, feel free to have a look [at my dotfiles](https://github.com/nekowinston/dotfiles/blob/main/home/apps/wezterm/bar.lua): <img alt="image" width="755" src="https://user-images.githubusercontent.com/79978224/224771749-3ba6e5db-47d5-453f-8de4-38ff75d1aa38.png">

Worked for me, just wanted to mention that said config has moved into it's own repo for anyone that comes across this. You can find it here now and has examples on how to use it https://github.com/nekowinston/wezterm-bar
