### ISSUE TITLE
Block cursor makes letter invisible

### ISSUE THREAD

**Issue by bomgar** [catppuccin/wezterm#13]
Hi,

using a block cursor (vi mode) makes the letters invisible. 
`config.force_reverse_video_cursor = true` fixes the problem but has other implications for the cursor color.
Maybe this can be fixed or mentioned in the readme.

**Comment by nekowinston** [comment]
What's your config & which vi mode are you using? This shouldn't happen.

**Comment by bomgar** [comment]
https://github.com/bomgar/dotfiles/blob/master/dot_config/wezterm/wezterm.lua#L39 (includes the video cursor setting at the moment. When I remove this it goes wrong)

neovim and fish vi mode both have that problem

**Comment by nekowinston** [comment]
Please use `config.color_scheme = "Catppuccin Mocha"`, not `catppuccin-mocha`, which is meant for iTerm.

**Comment by bomgar** [comment]
Thank you.
