### ISSUE TITLE
Tab bar colors won't change unless used as Wezterm plugin

### ISSUE THREAD

**Issue by zhengpd** [catppuccin/wezterm#16]
The tab bar colors only take effect if this is used as Wezterm plugin, since Wezterm use `window_frame` option to configure tab bar (https://github.com/wez/wezterm/issues/2615). The README is missing instruction for plugin usage:

```lua
local config = {}
local catppuccin = wezterm.plugin.require("https://github.com/catppuccin/wezterm.git")
catppuccin.apply_to_config(config, { flavor = "mocha" })
return config
```

**Comment by nithin-mk** [comment]
@zhengpd  The above config doesn't really change the colors of the fancy tab bar, ~~which I think is governed by the OS light or dark mode~~. When I changed your config to latte flavor, but Windows is in dark mode, my WezTerm tabs were black (active) or dark gray (inactive).

**Comment by nithin-mk** [comment]
Small correction: even in Windows light mode, the WezTerm tabs are still black or dark gray! So the OS mode doesn't change the tab bar color, only the title bar color.

**Comment by zhengpd** [comment]
@nithin-mk I haven't take a deep look on how options work since I'm using retro tab mode now. Last time I checked the `window_frame` option seems to be set properly. Maybe there is something not working in WezTerm side.
