### ISSUE TITLE
Move to Lua-only theme file

### ISSUE THREAD

**Issue by teenjuna** [catppuccin/wezterm#2]
Right now the theme is a bit divided: one part is in `colors/Catppuccin.toml` file, another part is directly in the `wezterm.lua`. This is a bit frustrating.

I propose to get rid of the `colors/Catppuccin.toml` file and implement the theme in a single `colors/Catppuccin.lua` file, like I did [here](https://github.com/teenjuna/configs/blob/aa81ad490cd667f18e516036a933b15800270a14/wezterm/colors/catppuccin.lua). Then just import the file in `wezterm.lua` like this:
```lua
local catppuccin = require("colors/Catppuccin")

return {
  colors = catppuccin,
  -- everything else
}
```

**Comment by LudoPinelli** [comment]
That's actually a very good idea, I'll make the changes as soon as I can, thanks :)
