### ISSUE TITLE
Invert tab background color for Latte (retro)

### ISSUE THREAD

**Issue by jfaz1** [catppuccin/wezterm#8]
I think it makes more sense for the dark gray tabs to be the ones that are unfocused, and the light one to be the active one for the retro style.

How it is right now:
![image](https://user-images.githubusercontent.com/56184947/190540222-1c4890ef-1c7f-466a-a1f0-7be309e8c789.png)

What I mean:
![image](https://user-images.githubusercontent.com/56184947/190540605-c797e946-8904-440f-bc18-53ea290aee9b.png)

**Comment by nekowinston** [comment]
Hi there 👋 
Thanks for your issue, I'd agree with that - are you using the TOML or Lua config?

**Comment by jfaz1** [comment]
> Hi there 👋 Thanks for your issue, I'd agree with that - are you using the TOML or Lua config?

I'm not sure, whichever is the one that comes with `wezterm` out of the box. This is what I'm currently doing in my `wezterm` config if it's any use:
```
local scheme = wezterm.color.get_builtin_schemes()['Catppuccin Latte']
local bg = scheme.tab_bar.active_tab.bg_color
scheme.tab_bar.active_tab.bg_color = scheme.tab_bar.inactive_tab.bg_color
scheme.tab_bar.inactive_tab.bg_color = bg
```

**Comment by nekowinston** [comment]
That'd be the TOML version - it will take until the next release of WezTerm to get inlcuded with the update. I'll push something soon.

**Comment by jfaz1** [comment]
> That'd be the TOML version - it will take until the next release of WezTerm to get inlcuded with the update. I'll push something soon.

Thanks! That's fine, my current config works for now. Feel free to close the issue when you change it.

**Comment by nekowinston** [comment]
I've changed both the Lua and the TOML files, this is how it should look by default with the next update, with Tab 2 being the active tab:

![image](https://user-images.githubusercontent.com/79978224/190560846-d035de1d-65c4-4e07-9d03-31eed8020de6.png)

**Comment by ChrHorn** [comment]
The new tab themes look different for me (TOML version). Contrast between active/inactive tab is a bit too low.

Mocha:
![image](https://user-images.githubusercontent.com/17070041/193447009-d2b8d4af-7df5-4575-a2c3-95608c7a6479.png)

Latte:
![image](https://user-images.githubusercontent.com/17070041/193447028-b4ff5309-97f0-480b-aac1-41ba227c3412.png)

**Comment by nekowinston** [comment]
Yeah I'd agree.
Do you think it'd look better if I flipped the unfocused tab grey and `+` grey around? @ChrHorn

This would also match @jfaz1 screenshot more closely. I'd have to handle Latte differently to the other flavours tho.

**Comment by ChrHorn** [comment]
This would look better, but not really fan of handling Latte differently. In my opinion i looked fine before this change. Having the selected tab same color as bg works when the button is bigger (e.g VSCode), but here it is so small, so you always run into contrast issues. Darker meaning selected for Latte is also consistent how it is used for most of the Catppuccin ports (checked fzf and nvim).

Could also copy the [Kitty ](https://github.com/catppuccin/kitty) port, they use Mauve for the selected tab.

**Comment by nekowinston** [comment]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/79978224/223002823-c2c46783-0260-4a97-a4a2-09699d7abdcb.png">
With #10, the theme switched to `mauve` for the active tab. The repo will get support to be used as a WezTerm plugin, where you can easily change that:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/79978224/223003045-4833b735-a9f3-490a-adf7-773c106260c1.png">
