### ISSUE TITLE
Which-key & Noice bg-color orange

### ISSUE THREAD

**Issue by mattiasbonte** [catppuccin/wezterm#9]
Hello,

I tried out the plugin, but I'm wondering why my which-key bg is orange and same for the noice prompt. Is this intended?
And if so, how could I best change it myself?
![image](https://user-images.githubusercontent.com/65280774/205522791-c4a31ef3-56c3-439b-9816-4ded60a01c7d.png)

Usually it would look like this for example.
![image](https://user-images.githubusercontent.com/65280774/205522835-355e117f-2fd3-4366-9b3b-f71e744b1830.png)

Thanks a lot!

**Comment by nekowinston** [comment]
Hi there :wave:

This seems like an issue with your neovim configuration, not WezTerm. Neovim uses hex colors like `#1e1e2e`, and doesn't reference your terminal colors.

Does this only appear in WezTerm?

**Comment by mattiasbonte** [comment]
That is correct. In kitty for example I don't seem to have this issue. 

And if I for example try the "Batman" wezterm theme it's black as expected.

**Comment by nekowinston** [comment]
Could you share your Neovim and WezTerm configurations? Without those, it's hard to guess where this issue is coming from.

**Comment by nekowinston** [comment]
I think I just realized what's happening. This issue is very likely not related to WezTerm, but to your use of tmux instead.

We're using `peach` for the indexed color 16.
https://github.com/catppuccin/wezterm/blob/abf490a413516863b44ed4c6b7e2c1e805630e07/dist/catppuccin-mocha.toml#L34-L36

16 is black in the 256-color xterm colorchart: https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
I'm pretty sure you're referring to the terminal color 16 somewhere in your vim, when you should be using `#000000` (or the respective background color for the theme).


As for how you could fix it - see the [FAQ](https://github.com/catppuccin/wezterm#-faq)
```lua
local custom = wezterm.color.get_builtin_schemes()["Catppuccin Mocha"]
custom.indexed = {
	[16] = nil,
}
```

**Comment by mattiasbonte** [comment]
Smart..! Thanks a lot for pointing that out to me. It indeed appears to be tmux.
 
I do have to admit that I have no idea what is causing this. It's not only inside neovim. Lazygit for example also shows issues when opened from wezterm attached to tmux. I've removed everything from within my tmux config. But it doesn't seem that anything within my config is causing this.

I'm also wondering why I'm not experiencing this from within kitty terminal. I do have the same colors in an un-configured Alacritty. Maybe kitty is doing some color magic I'm not aware of.

I know this might not be the right place to ask, but you appear to know your color stuff :) so I might ask it anyway. Do you maybe have an idea/hint for where I should look to solve these color issues with tmux?

If not, thanks a lot for your time!

**Comment by nekowinston** [comment]
> I'm also wondering why I'm not experiencing this from within kitty terminal. I do have the same colors in an un-configured Alacritty. Maybe kitty is doing some color magic I'm not aware of.

It seems to me that Kitty isn't fully [Catppuccin spec](https://github.com/catppuccin/catppuccin/blob/main/docs/style-guide.md#extended-colours) compliant, by only setting colors 0-15.
https://github.com/catppuccin/kitty/blob/main/mocha.conf#L48

> I know this might not be the right place to ask, but you appear to know your color stuff :) so I might ask it anyway. Do you maybe have an idea/hint for where I should look to solve these color issues with tmux?

With tmux, it's most often a wrong `$TERM` setting... you might get some warnings when you run `:CheckHealth` in nvim under tmux. I ran into color specific issues like this so frequently with tmux over the years that I switched from tmux to terminal emulators (like Kitty, WezTerm) for muxing. I know that they don't fully replace tmux 1:1, but overall the switch has been worth it.

**Comment by mattiasbonte** [comment]
That helped a lot. Much appreciated.

Adding this `set-option -g default-terminal "tmux-256color"` to my tmux config fixed it for me (on MacOs at least).

I have also considered the same a couple of times, but could really replace it session-wise. It's session persistence is something I haven't been able to replace properly. But maybe I haven't looked deep enough into wezterm..

Thanks a lot!
